### ISSUE TITLE
Admin user breaks the UI

### ISSUE THREAD

**Issue by vvalchev** [syzoj/syzoj-ng-demo#1]
On the ranking page, when I click on the admin user, the UI breaks because of some missing data.

It seems, that the following information has to be added to the database:
```
insert into user_information (userId,organization,location,url,telegram,qq,github) values (1,'','','','','','');
insert into user_preference (userId,preference) values (1,'{}');
```

**Comment by Menci** [comment]
Oh yes I missed to add them to SQL file after I changed the database structure.

**Comment by Menci** [comment]
Fixed
